### ISSUE TITLE
Output display does not make sense

### ISSUE THREAD

**Issue by KedrianLoh** [KedrianLoh/pe#1] opened 2023-04-14 08:37 UTC
![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/be80b7a2-e7f9-4e9e-83ff-f83d5b42feda.png)

![image.png](https://raw.githubusercontent.com/KedrianLoh/pe/main/files/e8975376-10a8-43a8-9d24-8be0433b465b.png)

The sorry message does not make any sense. Created 3 categories and used command "search test"

**Comment by nus-se-script** [comment] 2023-04-18 10:26
# Team's Response
Duplicate of #651.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Wrong UI message displayed
>
>![image.png](https://raw.githubusercontent.com/nus-cs2113-AY2223S2/pe/master/files/7bcb2a9b-6133-4cb4-bcb3-793aca7cf2fd.png)
>
>Even though the event/category matching `55` is not present in the list, the program still informs me that there are matching results by displaying `Sorry, there is matching search results.`, so it is confusing me.
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2223S2/pe-interim#523] [original labels: type.FunctionalityBug severity.Low]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>Yes, this is a typo where the word "no" is missing.
# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

<catcher-end-of-segment><hr>
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [x] I disagree

**Reason for disagreement:** Given that the search function is how users find out their different expenses and can be considered as extremely essential function of the program, having a confusing and incorrect message a function by saying something exists when it clearly does not, should have a severity of Low.

<catcher-end-of-segment><hr>

**Closed as completed** 2024-02-09 09:00 UTC
Labels: severity.Low, type.FunctionalityBug, status.Done
